import React from "react";
import {
  MapPin,
  Globe,
  Instagram,
  Mountain,
  Leaf,
  Snowflake,
  ShieldCheck,
} from "lucide-react";

const partners = [
  {
    name: "DC LifeSafe Global",
    location: "Colorado, USA",
    logo: "/logo_dclifesafeglobal_expeditions.png",
    image: "/card_global_expedition_network.png",
    accent: "orange",
    website: "https://www.dclifesafeglobal.com",
    instagram: "https://www.instagram.com/dclifesafeglobal",
    services: [
      "Wilderness Medicine",
      "Training & Education",
      "Expedition Leadership",
      "Resilience & Wellbeing",
      "Photography & Storytelling",
    ],
  },
  {
    name: "Viajeros Perú",
    location: "Ancón, Lima, Peru",
    logo: "/logo_viajerosperu.png",
    image: "/hero_viajerosperu.png",
    accent: "orange",
    website: "https://viajerosperu.pe",
    instagram: "https://www.instagram.com/viajerosperu",
    services: [
      "Trekking & Hiking",
      "Cultural Immersion",
      "Adventure Travel",
      "Multi-region Expeditions",
      "Logistics & Support",
    ],
  },
  {
    name: "T Viajes",
    location: "La Merced, Chanchamayo, Peru",
    logo: "/logo_tviajes.jpg",
    image: "/hero_tviajes.png",
    accent: "green",
    website: "",
    instagram: "https://www.instagram.com/tviajesperu",
    services: [
      "Central Jungle Expeditions",
      "Ecotourism & Nature",
      "Indigenous Communities",
      "Oxapampa – Villa Rica",
      "Sustainable Experiences",
    ],
  },
  {
    name: "ANTS Travel Smart",
    location: "Antarctica / International Operations",
    logo: "/logo_antstravelsmart.jpeg",
    image: "/hero_antstravelsmart.png",
    accent: "blue",
    website: "https://antstravelsmart.com",
    instagram: "https://www.instagram.com/
],
  },